### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [ministryofjustice/prisonstaffhub#413]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/ministryofjustice/prisonstaffhub/blob/master/package.json#L123

See https://nodejs.org/api/fs.html

You might want to remove it using `yarn remove fs`.

**Comment by jsrobertson** [comment]
Thanks @DanielRuf for the heads up.  Very much appreciated.
